const xml2js = require('xml2js');

const xmlData = `
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0">

<!-- Generated by One.com Web Editor -->

<url>
  <loc>https://devdxb6.1next.one/contact</loc>
  <lastmod>2024-12-13T12:58:52.285Z</lastmod>
</url>

<url>
  <loc>https://devdxb6.1next.one/</loc>
  <lastmod>2024-12-13T12:58:52.285Z</lastmod>
</url>

<url>
  <loc>https://devdxb6.1next.one/products</loc>
  <lastmod>2024-12-13T12:58:52.312Z</lastmod>
</url>

<url>
  <loc>https://devdxb6.1next.one/about-us</loc>
  <lastmod>2024-12-13T12:59:23.211Z</lastmod>
</url>

<url>
  <loc>https://devdxb6.1next.one/bookings</loc>
  <lastmod>2024-12-19T06:29:44.247Z</lastmod>
</url>

<url>
  <loc>https://devdxb6.1next.one/gallery</loc>
  <lastmod>2024-12-13T12:59:23.211Z</lastmod>
</url>

</urlset>
`;
const run = async () => {
  const parser = new xml2js.Parser();
  parser.parseString(xmlData, (err, result) => {
    if (err) {
      console.error(err);
      return;
    }
    console.log(JSON.stringify(result, null, 2));
  });
};

run();
